name: VeTube-x86

on:
  push:
    tags: ["*"]
    branches: [ master , piper ]
  pull_request:
    branches: [ master , piper ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [Win32]
        config: [Release]
        link: [dll]

        include:
        - link: dll
          shlib: "ON"

    steps:
      - name: Source checkout
        uses: actions/checkout@v3
        with:
          repository: rmcpantoja/espeak-ng
          path: espeak-ng
      - name: configure-espeak
        run: cd espeak-ng && cmake -Bbuild -DUSE_ASYNC:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shlib }} -A ${{ matrix.arch }} -DUSE_MBROLA:BOOL=OFF -DUSE_LIBSONIC:BOOL=OFF -DUSE_LIBPCAUDIO:BOOL=OFF -DUSE_KLATT:BOOL=OFF -DUSE_SPEECHPLAYER:BOOL=OFF -DEXTRA_cmn:BOOL=ON -DEXTRA_ru:BOOL=ON
      - name: make-espeak
        run: cd espeak-ng && cmake --build build --config ${{ matrix.config }}
      - uses: actions/checkout@v3
        with:
          path: VeTube
      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
          architecture: x86

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install Pillow==9.5.0
          pip install -r VeTube/requirements.txt
          pip install pyinstaller gdown
          pip install --upgrade pyzmq httpx httpcore future

      - name: Compiling
        run: |
          cd VeTube
          pyinstaller VeTube.py --windowed
          gdown 1ZtF6zus0A7kC9Lwr_kTUbw0MiOoZq29H -O dist/VeTube/bootstrap.exe
          cp -R chat_downloader dist/VeTube/
          cp -R doc dist/VeTube/
          cp -R locales dist/VeTube/
          cp -R sounds dist/VeTube/
          mkdir dist/VeTube/espeak-ng
          cp -R ../espeak-ng/build/src/release/espeak-ng.dll dist/VeTube/espeak-ng
          cp -R ../espeak-ng/build/espeak-ng-data dist/VeTube/espeak-ng
      - uses: actions/upload-artifact@v3
        with:
          name: VeTube-x86
          path: VeTube/dist/VeTube
          if-no-files-found: error
      - name: zip packaging
        run: |
          cd VeTube/dist/VeTube
          7z a ../../../VeTube-x86.zip .
          cd ../../../
      - name: vetube_release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: VeTube-x86.zip
          prerelease: ${{ contains(github.ref, '-') }}
